[package]
name = "spider"
version = "1.1.2"
authors = ["madeindjs <contact@rousseau-alexandre.fr>"]
description = "Multithreaded Web spider crawler written in Rust."
repository = "https://github.com/madeindjs/spider"
readme = "README.md"
keywords = ["crawler", "spider"]
categories = ["web-programming"]
license = "MIT"
documentation = "https://docs.rs/spider"

[badges]
maintenance = { status = "as-is" }

[dependencies]
reqwest = "0.9.22"
scraper = "0.11.0"
robotparser = "0.10"
url = "2.2.0"
